create database CAPAS_PRACTICA1;
GO

use CAPAS_PRACTICA1;
GO

CREATE TABLE ENCABEZADO_FACTURA(
ID_FACTURA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
FECHA DATETIME NOT NULL,
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
SUBTOTAL DECIMAL NOT NULL,
IMPUESTO DECIMAL NOT NULL,
MONTODESCUENTO DECIMAL
);	

CREATE TABLE DETALLE_FACTURA(
ID_FACTURA INT FOREIGN KEY REFERENCES ENCABEZADO_FACTURA(ID_FACTURA),
ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTOS(ID_PRODUCTO),
CANTIDAD INT NOT NULL
);

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
DESCRIPCION VARCHAR(35) NOT NULL,
PRECIOCOMPRA DECIMAL NOT NULL,
PRECIOVENTA DECIMAL NOT NULL,
GRAVADO VARCHAR(25) NOT NULL);

CREATE TABLE CLIENTES(
ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(11) NOT NULL,
DIRECCION VARCHAR(150) NOT NULL);

